### PR TITLE
road to bb: http client lite & bb tests

### PR DESCRIPTION
**Pull request by lread**
When running babashka, we now use the compatible http-client-lite.
- Thanks borkdude, your etaoin pod work was a very useful reference!
- I worked around an issue in http-client-lite when running on Windows.
See https://github.com/clj-commons/clj-http-lite/issues/18.

Reader conditionals select the existing http-client when running on from
the JVM.

Reader conditionals mean .cljc, which often means Clojure and
ClojureScript, but in our case it means JVM Clojure and Babashka
Clojure. Update configs for cljdoc and clj-kondo to let them know
that this is not a ClojureScript project.

Facility to test our bb implementation added via a new --platform option
on our `bb test` task. I'm not sure of the best way to run babashka
tests, but my first stab generates a runner.clj with appropriate
namespaces and classpath then runs that.

Etaoin does have some debug logging, so Babashka's log level is adjusted
from the default of debug to info in the generated test runner.

Finally adjusted our CI matrix to include the bb platform.

Contributes to https://github.com/clj-commons/etaoin/issues/380

### CODE REVIEW

**Comment by lread** [comment]
@borkdude, I'm sure some things can be done differently, but what do you think of this approach? Is generating a bb test runner a decent approach? I only noticed I maybe could be using [test-runner](https://github.com/babashka/babashka/blob/master/doc/projects.md#test-runner) after the fact.

**Comment by borkdude** [comment]
@lread Making a bespoke bb test runner is fine.

**Comment by borkdude** [comment]
@lread Ah, I now read the whole PR. Yeah, using the cognitect test runner may unify the tests for clojure and bb more? I'm surprised how little change it was to the actual library code :)

**Comment by lread** [comment]
@borkdude, thanks for reviewing!

I will take a crack at using the cognitect test-runner before merging.
Always excited to simplify an delete code!

And yes, I agree there wasn't a ton of change required to make this library bb compatible. I'll likely summarize in the closing PR which will include docs. I think most of my time was spent on Windows mysteries.

One thing that I found a little odd for this PR was [this io/resource Windows dance](https://github.com/clj-commons/etaoin/pull/438/files#diff-3ff977bd9426646f7154341a9ce50035fd409081ab3ad7ccf61091581a1b9473). Not sure if it is coming from Babashka but suspect maybe a Graalism? I can try to distill the symptom/work-around separately for Babashka if you like.

**Comment by borkdude** [comment]
The io/resource thing may be a bug. Feel free to provide a issue + repro.

**Comment by borkdude** [comment]
@lread Don't know if it was clear already, but you can use the cognitect test runner using this snippet in this README:

https://github.com/babashka/tools.namespace

**Comment by lread** [comment]
Ok, @borkdude the cognitect test-runner worked great! Gonna merge this puppy.

**Pull request merged**
