### PR TITLE
Fix #524: reflection for both bb and jvm

### LINKED ISSUE #524: etaoin fails with bb 1.2.174
The culprit is in `wait`. It has to do with: https://github.com/babashka/babashka/issues/1513
For now we'll work around it using a manual cast.

### PR DESCRIPTION
**Pull request by borkdude**
Please complete and include the following checklist:

- [x] I have read [CONTRIBUTING](https://github.com/clj-commons/etaoin/blob/master/CONTRIBUTING.md) and the [Etaoin Developer Guide](https://github.com/clj-commons/etaoin/blob/master/doc/02-developer-guide.adoc).

- [x] This PR corresponds to an issue that the Etaoin maintainers have agreed to address: https://github.com/clj-commons/etaoin/issues/524

- [x] This PR contains test(s) to protect against future regressions

- [x] I have updated [CHANGELOG.adoc](https://github.com/clj-commons/etaoin/blob/master/CHANGELOG.adoc) with a description of the addressed issue.

### CODE REVIEW

**Comment by dysmento** [comment]
I confirmed this fixes my one-line failure by checking out this branch and using `:local/root`

```
❯ bb --version
babashka v1.2.174

❯ bb -Sdeps '{:deps {etaoin/etaoin {:local/root "../etaoin"}}}' -e "(require '[etaoin.api :as e]) (def driver (e/chrome))"
2023-03-08T19:14:21.478Z L-SAN-220728-01 DEBUG [etaoin.api:?] - Created driver: chrome 127.0.0.1:62824
2023-03-08T19:14:21.502Z L-SAN-220728-01 DEBUG [etaoin.api:?] - Starting process: chromedriver --port=62824
2023-03-08T19:14:21.505Z L-SAN-220728-01 DEBUG [etaoin.api:?] - Waiting until 127.0.0.1:62824 is running
2023-03-08T19:14:22.846Z L-SAN-220728-01 DEBUG [etaoin.api:?] - Waiting until 127.0.0.1:62824 is running
2023-03-08T19:14:23.856Z L-SAN-220728-01 DEBUG [etaoin.impl.client:?] - chrome 127.0.0.1:62824   POST session {:desiredCapabilities {:loggingPrefs {:browser "ALL"}}}
#'user/driver
```

**Comment by lread** [comment]
Oh,`test-doc` seems to be consistently failing... will take a peek, fully expect not related to this PR.

**Comment by lread** [comment]
Or maybe failing inconsistently. I'll try one more rerun.

**Comment by lread** [comment]
Ok will deal with failing test-doc test separately #527. Merging.

**Pull request merged**
