### PR TITLE
Implement wait-downloaded

### PR DESCRIPTION
**Pull request by ageneau**

### CODE REVIEW

**Comment by igrishaev** [comment]
Hello @ageneau and sorry for such a delayed answer. Having the `wait-download` functionality is a really good idea, but honestly, I'm not sure about the implementation.

First, the pull request brings the two new dependencies that worries me:

```
[juxt/dirwatch "0.2.5"]
[org.clojure/core.async "1.3.610"]
```

Linking Etaoin with core.async is exactly what I'd like to avoid. I think you can just list the directory in a cycle during some certain time window or with the number of attempts.

**Comment by igrishaev** [comment]
I believe your PR might benefit from the following points:

- please do not add new dependencies;
- if the download dir is not set, throw an explicit exception saying that; just `:pre` is not enough.
- implement `wait-download` such that is uses the same thread in a cycle or a future with loop;

Alternatively, you can refactor your PR into a library that complements Etaoin.

**Review by igrishaev — CHANGES_REQUESTED** [review]
Please check out my last comment. Briefly: no new dependencies, use the same thread with max number of attempts & timeout.

**Comment by ageneau** [comment]
Hi. Thanks for the feedback. I'll try to work on this soon.

**Comment by lread** [comment]
@ageneau (or anybody else) is there still interest in this one?
If I don't hear back from you soon, I'll close this PR for now.

**Comment by lread** [comment]
Closing as stale. Feel free to re-open if you have an interest.

**Pull request closed without merging**
