### PR TITLE
Allow `webdriver-url` when creating drivers

### PR DESCRIPTION
**Pull request by verma**
>This is an optional pass-through property and web-driver requests are directly sent to this URL, instead of building the URL with host and port. This allows etaoin's use with service providers like browserstack.

Thanks a lot for your work on this project.

I have been trying to use etaoin to test some of my work, and wanted to integrate with browserstack. I made some changes to allow use of a 3rd party service through a `webservice-url` prop, which travels along with the driver and is used when its time to make a call (instead of host + port).

I would really appreciate some feedback and ways to make this better. E.g. may be we can decide on the web-driver URL to call during driver setup, instead of taking the host+port with us everywhere (with some indicator that the driver needs to be waited on to start before any tests could be run).

I couldn't find any particular tests for driver setup so I haven't included any, but I can work on that if its critical.

I have also only tested this using browserstack and a very simple script (open browser, goto google etc.), but I will run this through my test suite to see how it works.

```clojure
(with-chrome
    {:webdriver-url url
     :capabilities  {"os"              "Windows"
                     "os_version"      "10"
                     "browser"         "Chrome"
                     "browser_version" "80"
                     "name"            "My First Session"}}
    driver
    (doto driver
      (go "https://www.google.com")
      (wait 5)
      (quit)))
```

### CODE REVIEW

**Comment by verma** [comment]
I tested this code with a few more test cases from my test suite and it seems to be working well so far. I will continue testing and if there's something that needs updating I will update this PR accordingly.

**Comment by igrishaev** [comment]
Thanks a lot for your contribution, I'll have a look a bit later.

**Comment by verma** [comment]
Thank you for your interest.

I pushed some additional changes to allow for remote file uploads. These files are not hosted locally on the machine which is running the test suite, but rather on the remote webdriver host. E.g. browserstack provides certain files on their testing hosts which may be specified as `C:/Users/hello/url.txt`. Basically this change allows for pass-through of local validation of files.

Usage may be like:

```clojure
(upload-file driver (remote-file "C:/Users/hello/url.txt"))
```

I just wrap these types of files with a `RemoteFile` record (which is what the `remote-file` function does) so that we can continue using current mechanism of uploading files (through `defmethod`), without requiring additional arguments etc to show intent of local vs remote.

**Comment by mjmeintjes** [comment]
Just wanted to add that this pull request allows etaoin to work with browserless via their [webdriver api](https://docs.browserless.io/docs/selenium-library.html). Very useful.

```
  (e/with-chrome
    {:webdriver-url "https://chrome.browserless.io/webdriver"
     :capabilities {"browserless:token" "YOUR-API-TOKEN"
                    "chromeOptions" {"args" ["--no-sandbox"]}}}
    d
    (e/go d "https://en.wikipedia.org/" )
    (e/wait-visible d [{:id :simpleSearch} {:tag :input :name :search}])
    (e/fill d {:tag :input :name :search} "Clojure programming language")
    (e/fill d {:tag :input :name :search} keys/enter)
    (e/get-title d))

```

**Comment by lread** [comment]
Looks very interesting! 
I've got a bit of ramp-up to do, which might take a bit of time, but I'll certainly swing back to this PR.

**Comment by lread** [comment]
@verma I had a look and I like it!

It has been ages since you submitted this PR.
I am happy to handle the merge conflict.

One question because I am naive: why do we need to [strip-url-creds](https://github.com/clj-commons/etaoin/pull/357/files#diff-01bfceca3b11ebff5f0239412d7cfb27c75c34326d912f1c91dc73e5aec31a44R87)?

**Comment by verma** [comment]
@lread I think mostly for logging, the URL will work as is with the service if I recall correctly, but probably helpful to indicate where its connecting to help diagnose config issues.

Thanks for taking a look, 🙏🏽

**Comment by lread** [comment]
@mjmeintjes, thanks for this, I'll use it as an example in the user guide!

> Just wanted to add that this pull request allows etaoin to work with browserless via their [webdriver api](https://docs.browserless.io/docs/selenium-library.html). Very useful.
> 
> ```
>   (e/with-chrome
>     {:webdriver-url "https://chrome.browserless.io/webdriver"
>      :capabilities {"browserless:token" "YOUR-API-TOKEN"
>                     "chromeOptions" {"args" ["--no-sandbox"]}}}
>     d
>     (e/go d "https://en.wikipedia.org/" )
>     (e/wait-visible d [{:id :simpleSearch} {:tag :input :name :search}])
>     (e/fill d {:tag :input :name :search} "Clojure programming language")
>     (e/fill d {:tag :input :name :search} keys/enter)
>     (e/get-title d))
> ```

**Comment by lread** [comment]
Ok @verma, I've completed what seems good to me!
I'm going to go ahead and merge. 
If there is anything with my changes that you are concerned about or recommend lemme know and I can adapt.

**Comment by verma** [comment]
Thank you! 🎉

**Comment by lread** [comment]
My pleasure! Thanks for contributing!

**Pull request merged**
